# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build unsigned apk"
  lane :build_apk do
    gradle(task: "clean assembleRelease")
  end

  desc "Build unsigned bundle"
  lane :build_aab do
    gradle(task: "clean bundleRelease")
  end

  desc "Build and deploy bundle"
  lane :deploy do
    store_password = prompt(text: "Keystore Password: ", secure_text: true)
    key_password = prompt(text: "Alias Key Password: ", secure_text: true)
    version = prompt(text: "Semantic version of the bundle: ")
    track = prompt(text: "To what track do you want to deploy (internal|alpha|beta|production): ")
    releaseFilePath = File.join(Dir.pwd, "..", "keystore.jks")
    gradle(task: 'clean')
    increment_version_code(
      gradle_file_path: "app/build.gradle",
    )
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.version.name" => version,
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "furmeds-signing",
        "android.injected.signing.key.password" => key_password,
      }
    )
    upload_to_play_store(
      track: track
    )
  end
end
