# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build unsigned apk"
  lane :build_apk do
    gradle(task: "clean assembleRelease")
  end

  desc "Build unsigned bundle"
  lane :build_aab do
    gradle(task: "clean bundleRelease")
  end

  desc "Build and deploy bundle"
  lane :deploy do
    releaseFilePath = File.join(Dir.pwd, "..", "keystore.jks")
    gradle(task: 'clean')
    increment_version_code(
      gradle_file_path: "app/build.gradle",
    )
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.version.name" => ENV["ANDROID_APP_VERSION"],
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => ENV['ANDROID_KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['ANDROID_ALIAS_KEY_NAME'],
        "android.injected.signing.key.password" => ENV['ANDROID_ALIAS_KEY_PASSWORD'],
      }
    )
    upload_to_play_store(
      track: ENV['ANDROID_DEPLOY_TRACK']
    )
  end
end
