default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build unsigned apk"
  lane :build_apk do
    gradle(task: "clean assembleRelease")
  end

  desc "Build unsigned bundle"
  lane :build_aab do
    gradle(task: "clean bundleRelease")
  end

  desc "Build and deploy bundle"
  lane :deploy do
    releaseFilePath = File.join(Dir.pwd, "..", "keystore.jks")
    gradle(task: 'clean')
    currentVersionCode = google_play_track_version_codes(
      track: ENV['ANDROID_DEPLOY_TRACK']
    )
    sh("sed", "-i", "'s/versionCode = .*/versionCode = currentVersionCode[0] + 1/g'", "variables.gradle")
    sh("sed", "-i", "'s/versionName = .*/versionName = "ENV["ANDROID_APP_VERSION"]"/g'","variables.gradle")
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => ENV['ANDROID_KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['ANDROID_ALIAS_KEY_NAME'],
        "android.injected.signing.key.password" => ENV['ANDROID_ALIAS_KEY_PASSWORD'],
      }
    )
    upload_to_play_store(
      track: ENV['ANDROID_DEPLOY_TRACK']
    )
  end
end
