name: build_web_app

on:
  workflow_run:
    workflows: ["generate_semantic_version"]
    branches: ["main"]
    types:
      - completed

jobs:
  build_web_app:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build web app
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Build web app
        working-directory: ./app
        env:
          VERSION: ${{ steps.semver.outputs.version }}
        run: |
          echo "version: ${VERSION}"
          npm i -g @angular/cli
          npm ci
          ng build --configuration production
      - name: Upload www as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: www
          path: app/www
          retention-days: 3
